spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/danamon
    username: postgres
    password: wahyu
  jpa:
      hibernate:
        ddl-auto: update
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: danamon
    enabled: true
    clean-disabled: true
  mvc:
    async:
      request-timeout: 5000
  redis:
    host: 127.0.0.1
    port: 6379

danamon:
  app:
    jwt-cookie-name: danamon-be
    jwt-secret: ======================Danamon=Secret===========================
    jwt-expiration-ms: 86400000

server:
  error:
    include-message: always

setting:
  cache:
    redis:
      time-to-live: 5
