spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/danamon
    username: postgres
    password: wahyu
  jpa:
      hibernate:
        ddl-auto: update
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: danamon
    enabled: true
    clean-disabled: true

danamon:
  app:
    jwt-cookie-name: danamon-be
    jwt-secret: ======================Danamon=Secret===========================
    jwt-expiration-ms: 86400000

